# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowwizardformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Field'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date Field'), ('number', 'Number Field'), ('money', 'Money Field'), ('textarea', 'Text Area'), ('select', 'Select Box')], default='text', max_length=100),
        ),
    ]
